import { createContext, useState } from "react";

const GameContext = createContext();

function GameProvider({ children }) {
  const [data, setData] = useState([
    {
      letter: "A",
      name: "null",
      emoji: "\uD83E\uDEB5",
      prodSpeed: 1,
      value: 0,
      active: false,
      available: false,
    },
    {
      letter: "Z",
      name: "null",
      emoji: "\uD83E\uDEB5",
      prodSpeed: 1,
      value: 0,
      active: false,
      available: false,
    },
    {
      letter: "E",
      name: "null",
      emoji: "\uD83E\uDEB5",
      prodSpeed: 1,
      value: 0,
      active: false,
      available: false,
    },
    {
      letter: "R",
      name: "null",
      emoji: "\uD83E\uDEB5",
      prodSpeed: 1,
      value: 0,
      active: false,
      available: false,
    },
    {
      letter: "T",
      name: "Tree",
      emoji: "\uD83E\uDEB5",
      prodSpeed: 1,
      value: 0,
      active: false,
      available: true,
    },
    {
      letter: "Y",
      name: "null",
      emoji: "\uD83E\uDEB5",
      prodSpeed: 1,
      value: 0,
      active: false,
      available: false,
    },
    {
      letter: "U",
      name: "null",
      emoji: "\uD83E\uDEB5",
      prodSpeed: 1,
      value: 0,
      active: false,
      available: false,
    },
    {
      letter: "I",
      name: "null",
      emoji: "\uD83E\uDEB5",
      prodSpeed: 1,
      value: 0,
      active: false,
      available: false,
    },
    {
      letter: "O",
      name: "null",
      emoji: "\uD83E\uDEB5",
      prodSpeed: 1,
      value: 0,
      active: false,
      available: false,
    },
    {
      letter: "P",
      name: "null",
      emoji: "\uD83E\uDEB5",
      prodSpeed: 1,
      value: 0,
      active: false,
      available: false,
    },
    {
      letter: "Q",
      name: "null",
      emoji: "\uD83E\uDEB5",
      prodSpeed: 1,
      value: 0,
      active: false,
      available: false,
    },
    {
      letter: "S",
      name: "Stone",
      emoji: "\uD83E\uDEA8",
      prodSpeed: 1,
      value: 0,
      active: false,
      available: true,
    },
    {
      letter: "D",
      name: "null",
      emoji: "\uD83E\uDEB5",
      prodSpeed: 1,
      value: 0,
      active: false,
      available: false,
    },
    {
      letter: "F",
      name: "null",
      emoji: "\uD83E\uDEB5",
      prodSpeed: 1,
      value: 0,
      active: false,
      available: false,
    },
    {
      letter: "G",
      name: "Grass",
      emoji: "\uD83C\uDF3F",
      prodSpeed: 2,
      value: 0,
      active: false,
      available: true,
    },
    {
      letter: "H",
      name: "House",
      emoji: "\uD83D\uDED6",
      prodSpeed: 1,
      value: 0,
      active: false,
      available: false,
    },
    {
      letter: "J",
      name: "null",
      emoji: "\uD83E\uDEB5",
      prodSpeed: 1,
      value: 0,
      active: false,
      available: false,
    },
    {
      letter: "K",
      name: "null",
      emoji: "\uD83E\uDEB5",
      prodSpeed: 1,
      value: 0,
      active: false,
      available: false,
    },
    {
      letter: "L",
      name: "null",
      emoji: "\uD83E\uDEB5",
      prodSpeed: 1,
      value: 0,
      active: false,
      available: false,
    },
    {
      letter: "M",
      name: "null",
      emoji: "\uD83E\uDEB5",
      prodSpeed: 1,
      value: 0,
      active: false,
      available: false,
    },
    {
      letter: "W",
      name: "Water",
      emoji: "\uD83D\uDCA7",
      prodSpeed: 1,
      value: 0,
      active: false,
      available: true,
    },
    {
      letter: "X",
      name: "null",
      emoji: "\uD83E\uDEB5",
      prodSpeed: 1,
      value: 0,
      active: false,
      available: false,
    },
    {
      letter: "C",
      name: "null",
      emoji: "\uD83E\uDEB5",
      prodSpeed: 1,
      value: 0,
      active: false,
      available: false,
    },
    {
      letter: "V",
      name: "null",
      emoji: "\uD83E\uDEB5",
      prodSpeed: 1,
      value: 0,
      active: false,
      available: false,
    },
    {
      letter: "B",
      name: "null",
      emoji: "\uD83E\uDEB5",
      prodSpeed: 1,
      value: 0,
      active: false,
      available: false,
    },
    {
      letter: "N",
      name: "null",
      emoji: "\uD83E\uDEB5",
      prodSpeed: 1,
      value: 0,
      active: false,
      available: false,
    },
  ]);
  const [unlock, setUnlock] = useState(0);
  return (
    <GameContext.Provider value={{ data, setData, unlock, setUnlock }}>
      {children}
    </GameContext.Provider>
  );
}
const ExportContext = {
  GameContext,
  GameProvider,
};

export default ExportContext;
