import { createContext, useState } from "react";

const GameContext = createContext();

function GameProvider({ children }) {
  const [data, setData] = useState([
    {
      letter: "A",
      name: "Apple",
      emoji: "\uD83C\uDF4E",
      prodSpeed: 1,
      totalProdSpeed: 0,
      value: 0,
      active: false,
      available: false,
    },
    {
      letter: "Z",
      name: "Zen",
      emoji: "	\uD83E\uDDD8\uD83C\uDFFD\u200D\u2642\uFE0F",
      prodSpeed: 1,
      totalProdSpeed: 0,
      value: 0,
      active: false,
      available: false,
    },
    {
      letter: "E",
      name: "Economy",
      emoji: "\uD83C\uDFE6",
      prodSpeed: 1,
      totalProdSpeed: 0,
      value: 0,
      active: false,
      available: false,
    },
    {
      letter: "R",
      name: "Rock",
      emoji: "\uD83E\uDEA8",
      prodSpeed: 1,
      totalProdSpeed: 0,
      value: 0,
      active: false,
      available: false,
    },
    {
      letter: "T",
      name: "Tree",
      emoji: "\uD83C\uDF33",
      prodSpeed: 1,
      totalProdSpeed: 0,
      value: 0,
      active: false,
      available: false,
      consumptions: [
        { id: 20, amount: 0.5 },
        { id: 12, amount: 1 },
        { id: 11, amount: 1 },
      ],
    },
    {
      letter: "Y",
      name: "Yeaahhh",
      emoji: "\uD83D\uDE0E",
      prodSpeed: 1,
      totalProdSpeed: 0,
      value: 0,
      active: false,
      available: false,
    },
    {
      letter: "U",
      name: "University",
      emoji: "\uD83C\uDFEB",
      prodSpeed: 1,
      totalProdSpeed: 0,
      value: 0,
      active: false,
      available: false,
    },
    {
      letter: "I",
      name: "Iron",
      emoji: "	\uD83E\uDEA8",
      prodSpeed: 1,
      totalProdSpeed: 0,
      value: 0,
      active: false,
      available: false,
    },
    {
      letter: "O",
      name: "Oats",
      emoji: "\uD83C\uDF3E",
      prodSpeed: 1,
      totalProdSpeed: 0,
      value: 0,
      active: false,
      available: false,
    },
    {
      letter: "P",
      name: "Paper",
      emoji: "\uD83D\uDCDC",
      prodSpeed: 1,
      totalProdSpeed: 0,
      value: 0,
      active: false,
      available: false,
      consumptions: [
        { id: 4, amount: 0.5 },
        { id: 20, amount: 0.5 },
      ],
    },
    {
      letter: "Q",
      name: "Quartz",
      emoji: "\uD83D\uDC8E",
      prodSpeed: 1,
      totalProdSpeed: 0,
      value: 0,
      active: false,
      available: false,
    },
    {
      letter: "S",
      name: "Seed",
      emoji: "\uD83C\uDF31",
      prodSpeed: 1,
      totalProdSpeed: 0,
      value: 0,
      active: false,
      available: false,
    },
    {
      letter: "D",
      name: "Dirt",
      emoji: "\u26F0\uFE0F",
      prodSpeed: 2,
      totalProdSpeed: 0,
      value: 0,
      active: false,
      available: false,
    },
    {
      letter: "F",
      name: "Fire",
      emoji: "\uD83D\uDD25",
      prodSpeed: 1,
      totalProdSpeed: 0,
      value: 0,
      active: false,
      available: false,
    },
    {
      letter: "G",
      name: "Gold",
      emoji: "\uD83C\uDF3F",
      prodSpeed: 2,
      totalProdSpeed: 0,
      value: 0,
      active: false,
      available: false,
    },
    {
      letter: "H",
      name: "House",
      emoji: "\uD83D\uDED6",
      prodSpeed: 0.1,
      totalProdSpeed: 0,
      value: 0,
      active: false,
      available: false,
      consumptions: [{ id: 4, amount: 0.5 }],
    },
    {
      letter: "J",
      name: "Joy",
      emoji: "	\uD83D\uDE0A",
      prodSpeed: 1,
      totalProdSpeed: 0,
      value: 0,
      active: false,
      available: false,
    },
    {
      letter: "K",
      name: "Knowledge",
      emoji: "\uD83D\uDE80",
      prodSpeed: 1,
      totalProdSpeed: 0,
      value: 0,
      active: false,
      available: false,
    },
    {
      letter: "L",
      name: "Liquor",
      emoji: "\uD83E\uDD43",
      prodSpeed: 1,
      totalProdSpeed: 0,
      value: 0,
      active: false,
      available: false,
    },
    {
      letter: "M",
      name: "Meat",
      emoji: "\uD83E\uDD69",
      prodSpeed: 1,
      totalProdSpeed: 0,
      value: 0,
      active: false,
      available: false,
    },
    {
      letter: "W",
      name: "Water",
      emoji: "\uD83D\uDCA7",
      prodSpeed: 1,
      totalProdSpeed: 0,
      value: 0,
      active: false,
      available: true,
    },
    {
      letter: "X",
      name: "Xylophone",
      emoji: "\uD83C\uDFB5",
      prodSpeed: 1,
      totalProdSpeed: 0,
      value: 0,
      active: false,
      available: false,
    },
    {
      letter: "C",
      name: "Crafting tools",
      emoji: "\uD83D\uDEE0\uFE0F",
      prodSpeed: 1,
      totalProdSpeed: 0,
      value: 0,
      active: false,
      available: false,
    },
    {
      letter: "V",
      name: "Villager",
      emoji: "\uD83D\uDC64",
      prodSpeed: 0.1,
      totalProdSpeed: 0,
      value: 0,
      active: false,
      available: false,
      passivs: [{ id: 0, amount: 1 }],
    },
    {
      letter: "B",
      name: "Book",
      emoji: "\uD83D\uDCD6",
      prodSpeed: 1,
      totalProdSpeed: 0,
      value: 0,
      active: false,
      available: false,
    },
    {
      letter: "N",
      name: "Nirvana",
      emoji: "\u26E9\uFE0F",
      prodSpeed: 1,
      totalProdSpeed: 0,
      value: 0,
      active: false,
      available: false,
    },
  ]);
  const [unlock, setUnlock] = useState(0);
  const [popup, setPopup] = useState(false);

  return (
    <GameContext.Provider
      value={{ data, setData, unlock, setUnlock, popup, setPopup }}
    >
      {children}
    </GameContext.Provider>
  );
}
const ExportContext = {
  GameContext,
  GameProvider,
};

export default ExportContext;
